### ISSUE TITLE
Plugin main file parts

### ISSUE THREAD

**Issue by szepeviktor** [SebKay/wordpress-plugin-template#1]
@SebKay I'd like to give you the result of 7 years of research.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md

And some source code.
https://github.com/szepeviktor/small-project/blob/master/plugin-name.php

**Comment by SebKay** [comment]
Hey Vikor,

That's awesome. Thanks for this! 💪
